---
- name: Instalar y configurar Nginx
  hosts: nginx
  become: true
  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Iniciar servicio Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

- name: Instalar Jenkins y Configurar Jenkins
  hosts: jenkins
  become: yes
  vars:
    jenkins_hostname: jenkins.example.com
    jenkins_admin_username: admin
    jenkins_admin_password: admin

  tasks:
    - name: Actualizar repositorios
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar dependencias
      apt:
        name:
          - openjdk-8-jdk
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Añadir clave GPG de Jenkins
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Añadir repositorio de Jenkins
      ansible.builtin.apt_repository:
        repo: "deb https://pkg.jenkins.io/debian binary/"
        state: present

    - name: Instalar Jenkins
      apt:
        name: jenkins
        state: present

    - name: Detener el servicio de Jenkins
      systemd:
        name: jenkins
        state: stopped

    - name: Cambiar el puerto de Jenkins a 80
      lineinfile:
        path: /etc/default/jenkins
        regexp: "^HTTP_PORT=.*"
        line: "HTTP_PORT=80"
      notify:
        - start jenkins

  handlers:
    - name: start jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes