---
- name: Instalar y configurar Nginx
  hosts: nginx
  become: true
  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Iniciar servicio Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
        
- name: Instalar y configurar Jenkins
  hosts: jenkins
  become: true
  vars:
    jenkins_apt_repo_url: "https://pkg.jenkins.io/debian-stable"
    jenkins_http_port: "80"

  tasks:
    - name: Agregar repositorio de Jenkins al sistema de paquetes
      apt_repository:
        repo: "deb {{ jenkins_apt_repo_url }} binary/"

    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar Jenkins
      apt:
        name: jenkins
        state: present
        allow_unauthenticated: yes

    - name: Iniciar servicio de Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes
    
    - name: Cambiar puerto de Jenkins
      lineinfile:
        path: /etc/default/jenkins
        regexp: 'HTTP_PORT='
        line: 'HTTP_PORT={{ jenkins_http_port }}'
      notify:
        - Reiniciar servicio Jenkins

  handlers:
    - name: Reiniciar servicio Jenkins
      systemd:
        name: jenkins
        state: restarted